jobs:
  build:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        architecture: x64
    - name: Install Python requirements
      run: |
        python -m pip install --upgrade pip
	pip install -r requirements.txt
    - name: Run Python Tests
      uses: fylein/python-pytest-github-action@v1
      with:
        args: run: pytest -v
